name: Hexo Action 
on:
  push:
    branches:

      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:

    - name: 1. git checkout...

      uses: actions/checkout@v1

    - name: 2. setup nodejs...

      uses: actions/setup-node@v1
      
      with:
        node-version: '16.x'

    - name: 3. install hexo...

      run: |
        npm install hexo-cli -g
        npm install hexo-deployer-git --save
        npm install hexo-renderer-pug hexo-renderer-stylus
        npm install hexo-generator-search --save 
        npm install

    - name: 4. hexo generate public files...

      run: |
        hexo clean
        hexo g
    
    - name: Deploy to Github Pages
      env:
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/ZLLVZY/ZLLVZY.github.io
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        cd ./public && git config --global init.defaultBranch main && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" main:main
       
     

